[build]
  # This command will be run on Netlify's servers to install your dependencies.
  command = "npm install"
  # This is the directory where your serverless functions are located.
  functions = "src" # This is the directory Netlify scans for function files.
